# Palindrom Algorithmus

In [11]:
import numpy as np
import matplotlib.pyplot as plt

In [21]:
width = 10
result = np.zeros((width, width))

def reverse(number):
    return int(str(number)[::-1])

def is_palindrome(number):
    return reverse(number) == number

for x in range(width):
    for y in range(width):
        number = x * width + y
        count = 0
        while not is_palindrome(number):
            number += reverse(number)
            count += 1
        result[x, y] = count
print(result)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  1.  1.  1.  1.  1.  1.  2.]
 [ 1.  1.  0.  1.  1.  1.  1.  1.  2.  1.]
 [ 1.  1.  1.  0.  1.  1.  1.  2.  1.  2.]
 [ 1.  1.  1.  1.  0.  1.  2.  1.  2.  2.]
 [ 1.  1.  1.  1.  1.  0.  1.  2.  2.  3.]
 [ 1.  1.  1.  1.  2.  1.  0.  2.  3.  4.]
 [ 1.  1.  1.  2.  1.  2.  2.  0.  4.  6.]
 [ 1.  1.  2.  1.  2.  2.  3.  4.  0. 24.]
 [ 1.  2.  1.  2.  2.  3.  4.  6. 24.  0.]]
